### ISSUE TITLE
Only shows blackscreen when I start

### ISSUE THREAD

**Issue by vinipsmaker** [Immington-Industries/way-cooler#52]
However, app seems to be responsive. If I type `Alt + Shift + Esc` it closes.

From the docker build I learned I should see a mouse pointer. Is the graphics for that mouse pointer not included in the repos or something like that? `sway` works on my system and it also makes use of `wlc`. So I think the error is not on `wlc`. Ideas?

**Comment by SnirkImmington** [comment]
Can you give us some log output (for now setting `$WAY_COOLER_LOG=trace` should print to stdout, we're working on it)?

The docker is an old version, we had similar issues when upgrading. 

We had a similar bug before - does the screen turn funny colors if you open a program (we had it turn gray when we opened dmenu). The issues seem to be with the background (the Rust wayland crate doesn't always work, currently it's just powering backgrounds), we'll see if the issue is there in the logs. 

If you want to test it without setting the background, setting the `way_cooler.background` to an invalid color would cause the background to not be set.

**Comment by vinipsmaker** [comment]
> does the screen turn funny colors if you open a program (we had it turn gray when we opened dmenu)

I didn't manage to open any program. `Alt+d` and `Alt+Enter` makes no effect on visual output.

The same error also happens if I open `way-cooler` as a X client, so I'm not sure if it's a bug related to Wayland or internal to `way-cooler`. I'll generate the logs for you.

**Comment by Timidger** [comment]
It's almost certainly Way Cooler that's the problem, we were having similar problems on different devices ever since we implemented basic background support. Hopefully we can pin down what the issue is.

Another thing you can try doing is opening `Cargo.toml` and removing any mention of `dlopen`. It's supposed to dynamically load the library, but I was also having issues with that on one my Arch machines so try that.

**Comment by vinipsmaker** [comment]
Sorry about the delay, I was reading the logs to be sure no sensitive information about me was being sent (it stores my UID which I don't like, but I'll let you guys see it anyway).

[way-cooler-wayland.txt](https://github.com/Immington-Industries/way-cooler/files/417248/way-cooler-wayland.txt)
[way-cooler-x11.txt](https://github.com/Immington-Industries/way-cooler/files/417247/way-cooler-x11.txt)

**Comment by vinipsmaker** [comment]
> If you want to test it without setting the background, setting the `way_cooler.background` to an invalid color (such as the string "black" or "asdf") would cause the background to not be set.

It didn't help.

**Comment by vinipsmaker** [comment]
> Another thing you can try doing is opening `Cargo.toml` and removing any mention of `dlopen`.

It made a difference. I still can't seem to use it properly (no mouse pointer or open programs when I hit `Alt+d`/`Alt+Enter`), but the screen "turn funny colors".

**Comment by Timidger** [comment]
Ok, we think we might have zeroed in on the issue. Rust-wlc is only up-to-date with wlc 0.0.3, and right now the wlc in the Arch repos is on 0.0.5. There may have been some breaking changes between those versions that have affected Way Cooler. Can you try linking it against that version of the library?

**Comment by SnirkImmington** [comment]
Can confirm, was running on my machine with old wlc, updated and it broke. We will update rustwlc right away, we had been putting it off for the Reddit announcement.

**Comment by vinipsmaker** [comment]
I've managed to see the mouse pointer when building against way-cooler commit 35a4610ed31f32002b989e3c9c86131b02c070c5, however app freezes (but a simple kill will kill it, I don't need `kill -9`).

> Ok, we think we might have zeroed in on the issue. Rust-wlc is only up-to-date with wlc 0.0.3, and right now the wlc in the Arch repos is on 0.0.5. There may have been some breaking changes between those versions that have affected Way Cooler. Can you try linking it against that version of the library?

Will do. Just need a few minutes to build the correct package version.

**Comment by vinipsmaker** [comment]
> Can confirm, was running on my machine with old wlc

Can confirm as well. I just downgraded wlc to version 0.0.3 and I've managed to have way-cooler from most recent git version running sound.

> We will update rustwlc right away

That sounds great. Thank you.
:)

**Comment by Timidger** [comment]
Awesome to hear that we tracked this down. This means the docker image can be updated to the right version as well, for people who want to try out Way Cooler but don't have the benefit of running Arch to try your PKGBULID :). We should have it updated by tonight (EST), we'll close this issue when it's updated.

**Comment by vinipsmaker** [comment]
Thanks again.

**Comment by starfys** [comment]
Confirmed on my machine (Arch Linux) as well.
Downgraded wlc to 0.0.3
way-cooler now works correctly

**Comment by Timidger** [comment]
rust-wlc has been updated, as has Way Cooler (including the docker image!), so the PKGBUILD should just work now, no need to downgrade to v0.0.3. If there any other problems, feel free to comment and reopen this thread, I'm going to close it as fixed for now.

**Comment by SnirkImmington** [comment]
Fixes pushed to `v0.3.1`

**Comment by vinipsmaker** [comment]
> Fixes pushed to `v0.3.1`

Hi guys, sorry about the delay to update the ArchLinux recipes (a.k.a. AUR packages, PKGBUILD...), but I was testing many different build options to find out why the binary being produced was still showing the "same" (just the blackscreen part) problem.

After a while I found `cargo install` never produced an usable binary while `cargo build` was okay. I don't know why, but `cargo install` does something different that makes the generated binary unusable (app looks responsible, but only shows blackscreen).

**Comment by Timidger** [comment]
Hmm, interesting... Did you try removing dlopen from Cargo.toml again like last time? That wasn't having issues on our machines but we've had some trouble working with it, and that seems to cause a change last time. 

You might also want to double check it's linking to the right library when ldd when you use install it. 

We didn't try testing `cargo install`, we'll give it a try and get back to you

**Comment by Timidger** [comment]
Hmm, interesting. On my machine when I use `cargo install` I can open terminals and do things but a lot of the keybindngs aren't working correctly. Moving between windows works but I can't nest them or open dmenu...It's definitely opening the right configuration file too since it's symlinked in `~/.config/way-cooler/init.lua`.

Yours sounds like a different issue though, since you can't even open any programs. Not sure if it'll provide any more info, but maybe some more logs can help us track down what's wrong with Way Cooler installing on your machine? Feel free to purge any mention of your UID from it, that only has to do with setting up the IPC socket and shouldn't be causing problems.

@SnirkImmington, I know you changed some xkb things in the latest release, is it possible there was a regression there?

**Comment by vinipsmaker** [comment]
[I'm on a tight schedule this week](https://gist.github.com/vinipsmaker/4998ccfacb971a0dc1bd#timeline), so I can only get back to play with this project which has a high chance to be my next Desktop Shell and replace my years of loyalty to Enlightenment next week.

I hope to contribute back possibly (a lock screen maybe, stuff like that... and tracking down bugs).

**Comment by Timidger** [comment]
That's excellent to hear, happy to hear you're excited about the project. We'll continue to try and debug this on our side, and track down the other issue you pointed out in #56 and the issue I found in #57. These sound like recent regressions, and hopefully shouldn't be hard to track down. By the time you're ready next week we hopefully will have resolved these issues.

**Comment by Timidger** [comment]
I can reproduce the `cargo install` issue on my machine now, will report back if I find the issue.

**Comment by Timidger** [comment]
Hm, frankly @vinipsmaker I cannot reproduce the issue. I thought I did before, but that was just an out of date binary from a few months ago I had on my machine.

When you get the chance, can you send us the output of `ldd <way-cooler-binary>` (if it lists wlc pointing to a generic `libwlc.so`, use `ls -l` to give us what the library it ultimately points to to verify you are using the right version of wlc), the Way Cooler log, and your Cargo.toml and Cargo.lock. That would be the best way to narrow down what your environment is like and why it's behaving the way it is.

**Comment by vinipsmaker** [comment]
> When you get the chance, can you send us the output of [...]

[ldd-out.txt](https://github.com/Immington-Industries/way-cooler/files/419165/ldd-out.txt)
[ls-out.txt](https://github.com/Immington-Industries/way-cooler/files/419164/ls-out.txt)

> the Way Cooler log, and your Cargo.toml and Cargo.lock

Will have time next week.

**Comment by vinipsmaker** [comment]
This was the failing command:

    cargo install way-cooler --root "$pkgdir"

However, I can install `way-cooler` with the following command, running from the right folder:

    cargo install --root "$pkgdir"

I guess I was pulling the latest version from crates.io. It's working okay now.

**Comment by Timidger** [comment]
Good to hear, hopefully this problem will never happen again if/when we switch to statically linking wlc and distributing the full linked binary
